auto: true
server: true
permalink: none
baseurl: "http://testeroids.github.com/Testeroids"
exclude:
- .gitignore
- README.md

prose:
  rooturl: ""
  metadata: 
    _posts/articles: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: johndoe
      author: John Doe
      categories:
      - articles